tested env_posix ok.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,6 +1,15 @@
 # stackdb test makefile
+ifndef PREFIX
+ $(error Please use outermost makefile in stackdb directory)
+endif
+
+# feature flags
+export DEFINES = -D HAVE_FDATASYNC \
+				 -D HAVE_O_CLOEXEC
+				 
+# compiler and make flags
 CXX = g++
-CXXFLAGS = -Wall -g -I../src -I../include
+export CXXFLAGS = -Wall -g -I$(PREFIX)/src -I../include $(DEFINES)
 MAKEFLAGS = --warn-undefined-variables
 # suppress warnings for these
 CPPFLAGS=
@@ -13,11 +22,18 @@ SOURCES = $(shell find . -name '*.cpp')
 OBJECTS = $(patsubst ./%.cpp, %.o, $(SOURCES))
 EXECUTE = $(patsubst ./%.cpp, %, $(SOURCES))
 
-# specific rules
 test: stackdb $(OBJECTS) $(EXECUTE)
+	@echo "\ntests generated. try 'make runtest'"
+# sh don't understand equality opertor == as in bash, so use = instead
+runtest: stackdb $(OBJECTS) $(EXECUTE)
 	@for test in $(EXECUTE); do \
-		echo -n "Running $$test: \t" ;\
-		./$$test ;\
+		echo -n "Running $$test: " ;\
+		./$$test ; \
+		if [ $$? = 0 ] ; then \
+			echo "OK" ; \
+		else \
+			echo "FAILED!!!!!!!!" ; \
+		fi \
 	done
 
 stackdb:
